flags: {}
packages:
- './'
extra-deps:
- number-show-0.1.0.0
- pragmatic-show-0.1.2.1
- constrained-categories-0.4.1.0
- trivial-constraint-0.7.0.0
- free-vector-spaces-0.1.5.1
- linearmap-category-0.4.1.0
- vector-space-0.16
- spatial-rotations-0.1.0.1
- manifolds-core-0.6.0.0
- manifolds-0.6.0.0
- manifold-random-0.6.0.0
- colour-space-0.2.0.0
- cairo-0.13.8.2
- pango-0.13.8.2
- diagrams-cairo-1.4.2
- diagrams-gtk-1.4
- glib-0.13.8.0
- gtk-0.15.7
- gtk2hs-buildtools-0.13.8.3
resolver: lts-18.28
allow-newer: true
