flags: {}
packages:
- './'
extra-deps:
- number-show-0.1.0.0
- pragmatic-show-0.1.2.0
- constrained-categories-0.4.0.0
- trivial-constraint-0.4.0.0
- free-vector-spaces-0.1.5.0
- linearmap-category-0.3.5.0
- vector-space-0.15
- spatial-rotations-0.1.0.1
- manifolds-core-0.5.0.3
- manifolds-0.5.0.3
- manifold-random-0.5.0.3
- colour-space-0.1.4.0
- cairo-0.13.6.0
- pango-0.13.6.0
- diagrams-cairo-1.4.1
- diagrams-gtk-1.4
- glib-0.13.7.0
- gtk-0.14.7
- gtk2hs-buildtools-0.13.5.0
resolver: lts-12.0
allow-newer: true
